package(default_visibility = ["//visibility:public"])

cc_library(
    name = "logging",
    srcs = [
        "logging.cc",
    ],
    hdrs = [
        "logging.h",
    ],
)

cc_library(
    name = "task-runner",
    srcs = [
        "task-runner.cc",
    ],
    hdrs = [
        "task-runner.h",
    ],
)
